In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
x.shape


(5,)

In [8]:
np.arange(1,10,5)

array([1, 6])

In [9]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [10]:
x.size

5

In [13]:
x.itemsize


4

In [14]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
x = np.random.randint(0,10,5)

In [21]:
np.random.shuffle(x)

In [23]:
np.random.choice(x)



3

In [25]:
print(x)

[3 1 2 8 8]


In [2]:
from numpy import array
x = array([2,3,5])
y = ([1,3,5])

In [3]:
print(x)
print(y)

[2 3 5]
[1, 3, 5]


In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [2]:
np.sum(x)


15

In [3]:
np.sum(x)

15

In [4]:
np.max(x)

5

In [5]:
np.min(x)

1

In [6]:
np.shape(x)

(5,)

In [7]:
np.mean(x)

3.0

In [8]:
y = np.array([2,4,5,6,7])
print(y)

[2 4 5 6 7]


In [9]:
np.sum(x+y)


39

In [10]:
np.sum(y)

24

In [11]:
np.max(x+y)

12

In [12]:
print(x-y)
print(x*y)
print(x/y)

[-1 -2 -2 -2 -2]
[ 2  8 15 24 35]
[0.5        0.5        0.6        0.66666667 0.71428571]


In [13]:
x.var()

2.0

In [14]:
x.std()

1.4142135623730951

In [15]:

import numpy as np
z = np.array([[1,3,5],[2,4,6]])
print(z)

[[1 3 5]
 [2 4 6]]


In [16]:
z.sum(axis=1)

array([ 9, 12])

In [17]:
import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,3,67,8])
print(s1.cov(s2))

12.666666666666666


In [18]:
from sklearn import svm
from sklearn.svm import SVC

X = [[0, 1], [1, 2]]
y = [0, 1]


clf = svm.SVC()


clf.fit(X, y)


print(clf.predict([[2.0, 2.0]]))

[1]


In [19]:
import pandas as pd
col_list=["id","first","last","gender","Marks","selected"]
df = pd.read_csv("sample.csv",usecols=col_list)
print(df)
print(df.shape)
print(df.head(5))
print(df.describe())


   id        first       last  gender  Marks  selected
0   1        Leone    Debrick  Female     50      True
1   2       Romola  Phinnessy  Female     60     False
2   3         Geri      Prium    Male     65     False
3   4        Sandy   Doveston  Female     95     False
4   5      Jacenta     Jansik  Female     31      True
5   6  Diane-marie   Medhurst  Female     45      True
6   7       Austen       Pool    Male     45      True
7   8        Vanya    Teffrey    Male     70     False
8   9     Giordano      Elloy    Male     36     False
9  10       Rozele    Fawcett  Female     50     False
(10, 6)
   id    first       last  gender  Marks  selected
0   1    Leone    Debrick  Female     50      True
1   2   Romola  Phinnessy  Female     60     False
2   3     Geri      Prium    Male     65     False
3   4    Sandy   Doveston  Female     95     False
4   5  Jacenta     Jansik  Female     31      True
             id      Marks
count  10.00000  10.000000
mean    5.50000  54.700000


In [20]:
import pandas as pd

col_list=["id","first","last","gender","Marks","selected"]
df=pd.read_csv("sample.csv",usecols=col_list)



print(df)


mean1 = df["Marks"].mean()
sum1 = df["Marks"].sum()
max1 = df["Marks"].max()
min1 = df["Marks"].min()
count1 = df["Marks"].count()
median1 = df["Marks"].median()
std1 = df["Marks"].std()
var1 = df["Marks"].var()

print("Mean marks\n" + str(mean1))
print("Sum of the marks\n" + str(sum1))
print("Maximum of the marks\n" + str(max1))
print("Minimum of the marks\n" + str(min1))
print("Count of the marks\n" + str(count1))
print("Median of the marks\n" + str(median1))
print("Standard deviation of the marks\n" + str(std1))
print("Variance of the marks\n" + str(var1))
print("End of the summary\n")

   id        first       last  gender  Marks  selected
0   1        Leone    Debrick  Female     50      True
1   2       Romola  Phinnessy  Female     60     False
2   3         Geri      Prium    Male     65     False
3   4        Sandy   Doveston  Female     95     False
4   5      Jacenta     Jansik  Female     31      True
5   6  Diane-marie   Medhurst  Female     45      True
6   7       Austen       Pool    Male     45      True
7   8        Vanya    Teffrey    Male     70     False
8   9     Giordano      Elloy    Male     36     False
9  10       Rozele    Fawcett  Female     50     False
Mean marks
54.7
Sum of the marks
547
Maximum of the marks
95
Minimum of the marks
31
Count of the marks
10
Median of the marks
50.0
Standard deviation of the marks
18.666964283341724
Variance of the marks
348.4555555555555
End of the summary

