In [1]:
import numpy as np
from sklearn.decomposition import PCA


X = np.array([[2, 6],
              [1, 7]])

print("Original Dataset:")
print(X)


pca = PCA(n_components=2)


X_pca = pca.fit_transform(X)

print("\nPCA Transformed Data:")
print(X_pca)


print("\nExplained Variance:")
print(pca.explained_variance_)

print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)


X_inverse = pca.inverse_transform(X_pca)

print("\nReconstructed Dataset (Inverse Transform):")
print(X_inverse)

print("\nAre Original and Reconstructed datasets similar?")
print(np.allclose(X, X_inverse))

Original Dataset:
[[2 6]
 [1 7]]

PCA Transformed Data:
[[ 7.07106781e-01 -1.18606713e-17]
 [-7.07106781e-01 -1.18606713e-17]]

Explained Variance:
[1.00000000e+00 2.81351049e-34]

Explained Variance Ratio:
[1.00000000e+00 2.81351049e-34]

Reconstructed Dataset (Inverse Transform):
[[2. 6.]
 [1. 7.]]

Are Original and Reconstructed datasets similar?
True


In [1]:
import numpy as np


X = np.array([[3, 6],
              [4, 7]])

print("Original Matrix")
print(X)


mean = np.mean(X, axis=0)

print("Mean matrix")
print(mean)


X_centered = X - mean

print("Centered Matrix")
print(X_centered)


cov_matrix = np.cov(X_centered, rowvar=False)

print("Covariance Matrix")
print(cov_matrix)


eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues")
print(eigenvalues)

print("Eigenvectors")
print(eigenvectors)

Original Matrix
[[3 6]
 [4 7]]
Mean matrix
[3.5 6.5]
Centered Matrix
[[-0.5 -0.5]
 [ 0.5  0.5]]
Covariance Matrix
[[0.5 0.5]
 [0.5 0.5]]
Eigenvalues
[1.00000000e+00 1.11022302e-16]
Eigenvectors
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
